services:

  app:
    build: .
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    command: [ "sh", "-c", "/app/bin/dbmigrate up && /app/bin/api" ]
    restart: always

  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: scraper_db
      POSTGRES_USER: scraper_user
      POSTGRES_PASSWORD: scraper_pass
      TZ: Asia/Ho_Chi_Minh
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U scraper_user -d scraper_db" ]
      interval: 3s
      timeout: 5s
      retries: 5
    restart: always
