services:

  scraper-db:
    image: postgres:17-alpine
    environment:
      - POSTGRES_DB=scraper_db
      - POSTGRES_USER=scraper_user
      - POSTGRES_PASSWORD=scraper_pass
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U scraper_user -d scraper-db" ]
      interval: 3s
      timeout: 5s
      retries: 5
    restart: always
