components:
  schemas:
    internal_api_handlers_user.FormSignUp:
      properties:
        confirmPassword:
          type: string
        email:
          type: string
        password:
          minLength: 8
          type: string
      required:
      - confirmPassword
      - email
      - password
      type: object
    web-scraper_dev_internal_api_errors.Error:
      properties:
        error:
          type: string
      type: object
    web-scraper_dev_internal_api_errors.ValidationErrors:
      properties:
        errors:
          items:
            type: string
          type: array
          uniqueItems: false
      type: object
externalDocs:
  description: ""
  url: ""
info:
  contact:
    name: Dumindu Madunuwan
    url: https://www.linkedin.com/in/dumindunuwan
  description: This is a sample RESTful API for a Web Scraper
  license:
    name: MIT License
    url: https://github.com/dumindu/web-scraper/blob/main/LICENSE
  title: Web Scraper API
  version: "1.0"
openapi: 3.1.0
paths:
  /users/activate:
    post:
      description: |-
        Verify the user's email by using the given 6-character long code.
        If the code already expired, a new verification email will be sent with a new code.
      parameters:
      - description: Email
        in: query
        name: email
        required: true
        schema:
          type: string
      - description: Activation code
        in: query
        name: token
        required: true
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                type: object
          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/web-scraper_dev_internal_api_errors.Error'
          description: Bad Request
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/web-scraper_dev_internal_api_errors.Error'
          description: Unauthorized
        "409":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/web-scraper_dev_internal_api_errors.Error'
          description: Conflict
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/web-scraper_dev_internal_api_errors.Error'
          description: Internal Server Error
      summary: Activate user
      tags:
      - users
  /users/sign-up:
    post:
      description: |-
        User signup by using the given email and password.
        This will send the email verification email with a 6-character long code to the given email address.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/internal_api_handlers_user.FormSignUp'
        description: SignUp Form
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                type: object
          description: Created
        "400":
          content:
            application/json:
              schema:
                oneOf:
                - $ref: '#/components/schemas/web-scraper_dev_internal_api_errors.Error'
                - $ref: '#/components/schemas/web-scraper_dev_internal_api_errors.ValidationErrors'
          description: Bad Request
        "409":
          description: Conflict
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/web-scraper_dev_internal_api_errors.Error'
          description: Internal Server Error
      summary: User signup
      tags:
      - users
servers:
- url: localhost:8080/v1
