components:
  schemas:
    internal_api_handlers_user.FormSignIn:
      properties:
        email:
          type: string
        password:
          minLength: 8
          type: string
      required:
      - email
      - password
      type: object
    internal_api_handlers_user.FormSignUp:
      properties:
        confirmPassword:
          type: string
        email:
          type: string
        password:
          minLength: 8
          type: string
      required:
      - confirmPassword
      - email
      - password
      type: object
    internal_api_handlers_user.RespTokens:
      properties:
        access:
          type: string
        refresh:
          type: string
      type: object
    web-scraper_dev_internal_api_errors.Error:
      properties:
        error:
          type: string
      type: object
    web-scraper_dev_internal_api_errors.ValidationErrors:
      properties:
        errors:
          items:
            type: string
          type: array
          uniqueItems: false
      type: object
    web-scraper_dev_internal_model.KeywordDTO:
      properties:
        adCount:
          type: integer
        errorMessage:
          type: string
        htmlContent:
          type: string
        id:
          type: integer
        keyword:
          type: string
        linkCount:
          type: integer
        status:
          type: string
      type: object
externalDocs:
  description: ""
  url: ""
info:
  contact:
    name: Dumindu Madunuwan
    url: https://www.linkedin.com/in/dumindunuwan
  description: This is a sample RESTful API for a Web Scraper
  license:
    name: MIT License
    url: https://github.com/dumindu/web-scraper/blob/main/LICENSE
  title: Web Scraper API
  version: "1.0"
openapi: 3.1.0
paths:
  /keywords:
    get:
      description: Get the list of keywords uploaded by current user
      requestBody:
        content:
          application/json:
            schema:
              type: object
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/web-scraper_dev_internal_model.KeywordDTO'
                type: array
          description: OK
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/web-scraper_dev_internal_api_errors.Error'
          description: Unauthorized
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/web-scraper_dev_internal_api_errors.Error'
          description: Internal Server Error
      security:
      - BearerToken: []
      summary: Get the list of keywords
      tags:
      - keywords
    post:
      description: Upload the keywords CSV file to scrape on web
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: file
          text/csv:
            schema:
              type: file
        description: CSV file with keywords
        required: true
      responses:
        "202":
          content:
            application/json:
              schema:
                type: object
          description: Accepted
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/web-scraper_dev_internal_api_errors.Error'
          description: Bad Request
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/web-scraper_dev_internal_api_errors.Error'
          description: Unauthorized
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/web-scraper_dev_internal_api_errors.Error'
          description: Internal Server Error
      security:
      - BearerToken: []
      summary: Upload the keywords CSV file
      tags:
      - keywords
  /keywords/{id}:
    get:
      description: Get the result of a keyword uploaded by current user
      parameters:
      - description: Keyword ID in uuid format
        in: path
        name: id
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/web-scraper_dev_internal_model.KeywordDTO'
          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/web-scraper_dev_internal_api_errors.Error'
          description: Bad Request
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/web-scraper_dev_internal_api_errors.Error'
          description: Unauthorized
        "404":
          description: Not Found
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/web-scraper_dev_internal_api_errors.Error'
          description: Internal Server Error
      security:
      - BearerToken: []
      summary: Get the result of a keyword
      tags:
      - keywords
  /users/activate:
    post:
      description: |-
        Verify the user's email by using the given 6-character long code.
        If the code already expired, a new verification email will be sent with a new code.
      parameters:
      - description: Email
        in: query
        name: email
        required: true
        schema:
          type: string
      - description: Activation code
        in: query
        name: token
        required: true
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                type: object
          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/web-scraper_dev_internal_api_errors.Error'
          description: Bad Request
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/web-scraper_dev_internal_api_errors.Error'
          description: Unauthorized
        "409":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/web-scraper_dev_internal_api_errors.Error'
          description: Conflict
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/web-scraper_dev_internal_api_errors.Error'
          description: Internal Server Error
      summary: Activate user
      tags:
      - users
  /users/sign-in:
    post:
      description: Login by using an email and a password.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/internal_api_handlers_user.FormSignIn'
        description: SignIn Form
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/internal_api_handlers_user.RespTokens'
          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/web-scraper_dev_internal_api_errors.Error'
          description: Bad Request
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/web-scraper_dev_internal_api_errors.Error'
          description: Unauthorized
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/web-scraper_dev_internal_api_errors.Error'
          description: Forbidden
        "409":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/web-scraper_dev_internal_api_errors.Error'
          description: Conflict
        "422":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/web-scraper_dev_internal_api_errors.Error'
          description: Unprocessable Entity
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/web-scraper_dev_internal_api_errors.Error'
          description: Internal Server Error
      summary: User Signin
      tags:
      - users
  /users/sign-up:
    post:
      description: |-
        User signup by using the given email and password.
        This will send the email verification email with a 6-character long code to the given email address.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/internal_api_handlers_user.FormSignUp'
        description: SignUp Form
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                type: object
          description: Created
        "400":
          content:
            application/json:
              schema:
                oneOf:
                - $ref: '#/components/schemas/web-scraper_dev_internal_api_errors.Error'
                - $ref: '#/components/schemas/web-scraper_dev_internal_api_errors.ValidationErrors'
          description: Bad Request
        "409":
          description: Conflict
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/web-scraper_dev_internal_api_errors.Error'
          description: Internal Server Error
      summary: User signup
      tags:
      - users
servers:
- url: localhost:8080/v1
