name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.x

      - name: Checkout code
        uses: actions/checkout@v4

      - name: go mod package cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Tests
        run: go test ./...

      - name: Gofumpt
        run: ./.github/workflows/bin/gofumpt -l -w . 2>&1 | tee outfile && test -z "$(cat outfile)" && rm outfile

      - name: Go Vet
        run: go vet ./...

      - name: Staticcheck
        run: ./.github/workflows/bin/staticcheck ./...

      - name: Govulncheck
        run: ./.github/workflows/bin/govulncheck ./...

      - name: OpenAPI specification errors
        run: ./.github/workflows/bin/swag init -g cmd/api/main.go -o . -ot yaml --v3.1 --parseDependency && mv swagger.yaml openapi-v3.1.0.yml
